POST http://localhost/api/login
Accept: application/json
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password",
  "device_name": "PHPStorm"
}

###
GET http://localhost/api/user
Accept: application/json
Authorization: Bearer 9a546244-851f-48ba-8076-5d40214001a0|a8jNTOJASA23JfF4evyvR322jb8oFAH4Q6AsrOAq202bdbf9
