POST http://localhost/api/login
Accept: application/json
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password",
  "device_name": "PHPStorm"
}

###
POST https://laravel.test/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "marcelocorrea229@gmail.com",
    "password": "Marsc2014"
}

###
GET https://laravel.test/api/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xhcmF2ZWwudGVzdC9hcGkvbG9naW4iLCJpYXQiOjE2OTczMzYxNzUsImV4cCI6MTY5NzMzOTc3NSwibmJmIjoxNjk3MzM2MTc1LCJqdGkiOiJDeFYwcTI4bkpCTWdiVENiIiwic3ViIjoiOWE1OTNkMjktZDllZi00ZDA4LWE0NjktMTM4MzkyZTYyODc3IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.jZlbBhR83Q-DYJ6_mZnUmpEmHEfG6C_OOd5xz_wnDNk
